export const menus = [
  {
    id: 1,
    title: 'Dashboard',
    icon: 'humbleicons:dashboard',
    route: 'inicio',
    menuKey: 'dashboard',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    title: 'Ações',
    icon: 'uil:action',
    route: 'acoes',
    menuKey: 'actions',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    title: 'Análises',
    icon: 'uil:graph-bar',
    route: 'analises',
    menuKey: 'reports',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    title: 'Consultores',
    icon: 'uil:shield-person',
    route: 'consultores',
    menuKey: 'consultants',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    title: 'Clientes',
    icon: 'uil:shake-hands-line',
    route: 'clientes',
    menuKey: 'customers',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    title: 'Empresas',
    icon: 'uil:buildings-bold',
    route: 'empresas',
    menuKey: 'companies',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    title: 'Menus',
    icon: 'uil:menu-round',
    route: 'menus',
    menuKey: 'menus',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8,
    title: 'Perfis de Acessos',
    icon: 'uil:profile',
    route: 'perfis-de-acessos',
    menuKey: 'roles',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9,
    title: 'Usuários',
    icon: 'mat_outline:group',
    route: 'usuarios',
    menuKey: 'users',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const companyAdminMenus = [
  {
    id: 1,
    title: 'Dashboard',
    icon: 'humbleicons:dashboard',
    route: 'inicio',
    menuKey: 'dashboard',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    title: 'Análises',
    icon: 'uil:graph-bar',
    route: 'analises',
    menuKey: 'reports',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    title: 'Consultores',
    icon: 'uil:shield-person',
    route: 'consultores',
    menuKey: 'consultants',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    title: 'Clientes',
    icon: 'uil:shake-hands-line',
    route: 'clientes',
    menuKey: 'customers',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
